install:
	curl -Lo iobin.zip http://iobin.suspended-chord.info/linux/iobin-linux-x64-deb-current.zip
	unzip iobin.zip
	sudo dpkg --add-architecture amd64
	sudo dpkg -i IoLanguage-*.deb
	rm -rf IoLanguage-*.deb iobin.zip

