PREFIX ?= /usr/local

.PHONY: install

# This is the only necessary target in the Makefile
# and it's expected to place the language interpretter
# or compiler in the path.
install:
	mv zombie.py $(PREFIX)/bin/zombie
	chmod +x $(PREFIX)/bin/zombie
